server:
  port: 10010
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HuangGitHubCode/gift-config.git
          force-pull: true